#!/usr/bin/env bash
# Generate .env secrets and a local log under .secrets/ (both gitignored).
# Re-run to rotate; back up first if you have live data (Twenty/n8n use these keys).

set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

mkdir -p .secrets

PG_DATABASE_PASSWORD="$(openssl rand -hex 16)"
APP_SECRET="$(openssl rand -base64 32)"
N8N_ENCRYPTION_KEY="$(openssl rand -base64 48)"
META_VERIFY_TOKEN="$(openssl rand -hex 16)"
GENERATED_AT="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

# Preserve existing non-secret lines from .env.example structure
cat > .env << EOF
# --- Generated by scripts/generate-secrets.sh at ${GENERATED_AT} ---
# Do not commit this file.

TWENTY_TAG=latest
TWENTY_HTTP_PORT=3020
SERVER_URL=http://localhost:3020
PG_DATABASE_USER=postgres
PG_DATABASE_PASSWORD=${PG_DATABASE_PASSWORD}
PG_DATABASE_NAME=default
PG_DATABASE_PORT=5432
REDIS_URL=redis://twenty-redis:6379
APP_SECRET=${APP_SECRET}
STORAGE_TYPE=local
STORAGE_S3_REGION=
STORAGE_S3_NAME=
STORAGE_S3_ENDPOINT=

TWENTY_INTERNAL_BASE=http://twenty-server:3000
TWENTY_API_KEY=

N8N_TAG=latest
N8N_HTTP_PORT=5678
N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
N8N_HOST=localhost
N8N_PROTOCOL=http
N8N_WEBHOOK_URL=http://localhost:5678/
GENERIC_TIMEZONE=UTC

BRIDGE_HTTP_PORT=3099
N8N_FORWARD_WEBHOOK_URL=
LOG_LEVEL=info

META_APP_SECRET=
META_VERIFY_TOKEN=${META_VERIFY_TOKEN}

TWILIO_AUTH_TOKEN=
TWILIO_WEBHOOK_PUBLIC_URL=
EOF

LOG=".secrets/secrets-log.md"
cat > "$LOG" << EOF
# AntiTrader — local secrets log

**Generated:** ${GENERATED_AT} (UTC)  
**Do not commit.** This folder is gitignored.

## Values (store in a password manager too)

| Name | Value |
|------|-------|
| PG_DATABASE_PASSWORD | \`${PG_DATABASE_PASSWORD}\` |
| APP_SECRET | \`${APP_SECRET}\` |
| N8N_ENCRYPTION_KEY | \`${N8N_ENCRYPTION_KEY}\` |
| META_VERIFY_TOKEN | \`${META_VERIFY_TOKEN}\` |

Paste **TWENTY_API_KEY** from Twenty → Settings → APIs & Webhooks into \`.env\` (required for n8n → Twenty HTTP).  
Paste **META_APP_SECRET** from Meta App Dashboard into \`.env\` when you configure WhatsApp.  
Paste **TWILIO_AUTH_TOKEN** from Twilio into \`.env\` when you configure SMS.

## What each secret does (encryption / signing)

| Secret | Role |
|--------|------|
| **PG_DATABASE_PASSWORD** | PostgreSQL user password (data at rest = disk encryption of your host/volume; not “field-level encryption” inside Twenty). |
| **APP_SECRET** | Twenty server session/signing secret — required for cookies/JWT-style server crypto (see Twenty docs). |
| **N8N_ENCRYPTION_KEY** | n8n uses this to **encrypt stored credentials** (API keys inside n8n DB). If you change it, existing stored credentials may break — rotate carefully. |
| **META_VERIFY_TOKEN** | Random string you also enter in Meta’s webhook “Verify token” field — **not** Meta’s App Secret. |
| **META_APP_SECRET** | From Meta app — used to verify **X-Hub-Signature-256** on inbound webhooks (set manually when you have an app). |

## Rotation

1. Stop stack: \`docker compose down\`
2. Re-run: \`./scripts/generate-secrets.sh\` (generates new values — **destructive** for n8n if N8N_ENCRYPTION_KEY changes)
3. For **n8n only**: prefer backing up \`n8n-data\` volume before changing \`N8N_ENCRYPTION_KEY\`.

EOF

chmod 600 .env 2>/dev/null || true
chmod 600 "$LOG" 2>/dev/null || true

echo "Wrote ${ROOT}/.env and ${ROOT}/${LOG}"
echo "Permissions set to 600 where supported."
